[package]
name = "rustash"
version = "0.2.2"
edition = "2021"
description = "a simple CLI tool to manage your notes"
license = "MIT"

[dependencies]
dirs = "5.0.1"

[[bin]]
name = "rustash"
path = "src/main.rs"
