[package]
name = "rustash"
version = "0.3.0"
edition = "2021"
description = "a simple CLI tool to manage your notes"
license = "MIT"

[dependencies]
dirs = "5.0.1"

[[bin]]
name = "rustash"
path = "src/main.rs"
